---
# X-Road Central Server Administration Port LoadBalancer Service
# Exposes port 4001 (admin interface) via MetalLB
apiVersion: v1
kind: Service
metadata:
  name: xroad-cs-admin-lb
  namespace: im-ns
  labels:
    app.kubernetes.io/name: xroad-central-server
    app.kubernetes.io/component: central-server
    app.kubernetes.io/part-of: x-road-information-mediator
    govstack.im/port-type: admin
  annotations:
    metallb.io/loadBalancerIPs: 10.0.0.100
    metallb.io/allow-shared-ip: "cluster-shared"
    govstack.im/port-description: "X-Road Central Server administration interface"
    govstack.im/external-port: "4001"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
    - name: admin
      protocol: TCP
      port: 4001
      targetPort: 4001
  selector:
    app.kubernetes.io/name: xroad-central-server
    app.kubernetes.io/component: central-server
